version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    default_reviewers:
    - davidgpgr94
    default_assignees:
    - davidgpgr94
    default_labels:
    - dependencies
    - dependabot
    commit_message:
      prefix: "chore"
      include_scope: true
